### ISSUE TITLE
Not working in Ionic3 project

### ISSUE THREAD

**Issue by elmartino** [theunreal/ngx-basicscroll#1]
Hi, I tried the ngx-basicScroll, but i can't get it working in an Ionic3 project. It says basicScroll is not found. Have you got it working in ionic3?

Thanks!

**Comment by theunreal** [comment]
Hi @elmartino, can you try to include basicScroll in your npm install command?

`npm install --save ngx-basicscroll basicscroll`

**Comment by elmartino** [comment]
yeah basicscroll is installed..

**Comment by elmartino** [comment]
The error is gone now, and i can add a component in my html like:

```
<bs-element [type]="'translateX'" [fromPosition]="'bottom-bottom'" [toPosition]="'top-middle'" [fromValue]="0" [toValue]="'400px'">
    <h2>Test</h2>
</bs-element>
```

Unfortunately nothing is happing on scroll.. The element is only moving when resising my screen a bit..
 Update: when doing the exact same in a new Angular project it is working..

It looks like the scroll event is not being received.

Thanks in advance!

**Comment by theunreal** [comment]
Please upload a reproduction to Stackblitz at: https://stackblitz.com/edit/angular-yaybdb

**Comment by elmartino** [comment]
I used an ionic project because i have the issue in ionic (it's also angular) Please see: https://stackblitz.com/edit/ionic-ayrium?file=app%2Fapp.module.ts 

I now get this error: package basic scroll not found. If i click install missing dependency i get the error below (see the capital S here). 

![image](https://user-images.githubusercontent.com/23487045/39313785-2077634a-4973-11e8-8b8e-33d26ac9a540.png)

The actual problem is something different, but this has to be fixed first. (I also had this locally and suddenly it worked, don't know why)

**Comment by theunreal** [comment]
**Please use the new updated library API and check the new usage information.**

Let me know if you face any issue.

**Comment by theunreal** [comment]
Closed due to inactivity
